jobs:

- job: build_and_test
  displayName:  'Test using '
  pool:
    vmImage: 'Ubuntu 16.04'
  strategy:
    matrix:
      pip-gcc4:
        gccVersion: '4.9'
        installWithPip: 'true'
      openmp-conda-gcc4:
        gccVersion: '4.9'
        useOpenMP: 'true'
      conda-gcc5:
        gccVersion: '5'
      ops-conda-gcc7:
        gccVersion: '7'
        devitoBackend: 'ops'
      yask-conda-gcc7:
        gccVersion: '7'
        devitoBackend: 'yask'
      conda-gcc8:
        gccVersion: '8'

  timeoutInMinutes: 120
  steps:
  - task: Docker@1
    displayName: "Build container"
    inputs:
      command: 'build'
      dockerFile: Dockerfile.pipelines
      arguments:
        --build-arg gccvers=$(gccVersion)
        --build-arg installWithPip=$(installWithPip)
        --build-arg backend=$(devitoBackend)
        --build-arg openmp=$(useOpenMP)
  - task: Docker@1
    displayName: "Run tests"
    inputs:
      command: 'run'
      runInBackground: false
